server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Sert le fichier demandé sinon retombe sur index.html
        try_files $uri $uri/ /index.html;
    }
}